name: Deploy to Netlify Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} https://api.netlify.com/build_hooks/600a73bff15c30959a28f4d4